version: '2'
services:
    jhipsternocachesampleapplication-sonar:
        container_name: jhipsternocachesampleapplication-sonar
        image: sonarqube:6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
